-- Destination Neon permissions preserve the source role access map.
BEGIN;
GRANT legacy_authenticated TO authenticated;
GRANT anon TO anonymous;
CREATE ROLE execom_service NOLOGIN;
GRANT execom_service TO authenticator;
GRANT USAGE ON SCHEMA public,auth TO authenticated,anonymous,execom_service;
GRANT EXECUTE ON FUNCTION auth.uid(),auth.role(),auth.jwt(),auth.email() TO authenticated,anonymous,execom_service;
REVOKE ALL ON ALL TABLES IN SCHEMA public FROM PUBLIC,anon,anonymous,authenticated,legacy_authenticated;
REVOKE EXECUTE ON ALL FUNCTIONS IN SCHEMA public FROM PUBLIC,anon,anonymous,authenticated,legacy_authenticated;
GRANT SELECT,INSERT,UPDATE,DELETE ON ALL TABLES IN SCHEMA public TO execom_service;
GRANT USAGE,SELECT ON ALL SEQUENCES IN SCHEMA public TO authenticated,anonymous,execom_service;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA public TO execom_service;
GRANT SELECT,INSERT,UPDATE,DELETE ON public."profiles" TO anonymous;
GRANT SELECT,INSERT,UPDATE,DELETE ON public."profiles" TO authenticated;
ALTER TABLE public."profiles" ENABLE ROW LEVEL SECURITY;
CREATE POLICY execom_server_access ON public."profiles" TO execom_service USING (true) WITH CHECK (true);
GRANT SELECT,INSERT,UPDATE,DELETE ON public."files" TO anonymous;
GRANT SELECT,INSERT,UPDATE,DELETE ON public."files" TO authenticated;
ALTER TABLE public."files" ENABLE ROW LEVEL SECURITY;
CREATE POLICY execom_server_access ON public."files" TO execom_service USING (true) WITH CHECK (true);
GRANT SELECT,INSERT,UPDATE,DELETE ON public."prototype_assessment_queue" TO anonymous;
GRANT SELECT,INSERT,UPDATE,DELETE ON public."prototype_assessment_queue" TO authenticated;
GRANT SELECT,INSERT,UPDATE,DELETE ON public."claim_outputs" TO anonymous;
GRANT SELECT,INSERT,UPDATE,DELETE ON public."claim_outputs" TO authenticated;
ALTER TABLE public."claim_outputs" ENABLE ROW LEVEL SECURITY;
CREATE POLICY execom_server_access ON public."claim_outputs" TO execom_service USING (true) WITH CHECK (true);
GRANT SELECT,INSERT,UPDATE,DELETE ON public."reviews" TO anonymous;
GRANT SELECT,INSERT,UPDATE,DELETE ON public."reviews" TO authenticated;
ALTER TABLE public."reviews" ENABLE ROW LEVEL SECURITY;
CREATE POLICY execom_server_access ON public."reviews" TO execom_service USING (true) WITH CHECK (true);
GRANT SELECT,INSERT,UPDATE,DELETE ON public."review_comments" TO anonymous;
GRANT SELECT,INSERT,UPDATE,DELETE ON public."review_comments" TO authenticated;
ALTER TABLE public."review_comments" ENABLE ROW LEVEL SECURITY;
CREATE POLICY execom_server_access ON public."review_comments" TO execom_service USING (true) WITH CHECK (true);
GRANT SELECT,INSERT,UPDATE,DELETE ON public."audit_log" TO anonymous;
GRANT SELECT,INSERT,UPDATE,DELETE ON public."audit_log" TO authenticated;
ALTER TABLE public."audit_log" ENABLE ROW LEVEL SECURITY;
CREATE POLICY execom_server_access ON public."audit_log" TO execom_service USING (true) WITH CHECK (true);
GRANT SELECT,INSERT,UPDATE,DELETE ON public."companies" TO anonymous;
GRANT SELECT,INSERT,UPDATE,DELETE ON public."companies" TO authenticated;
ALTER TABLE public."companies" ENABLE ROW LEVEL SECURITY;
CREATE POLICY execom_server_access ON public."companies" TO execom_service USING (true) WITH CHECK (true);
GRANT SELECT,INSERT,UPDATE,DELETE ON public."projects" TO anonymous;
GRANT SELECT,INSERT,UPDATE,DELETE ON public."projects" TO authenticated;
ALTER TABLE public."projects" ENABLE ROW LEVEL SECURITY;
CREATE POLICY execom_server_access ON public."projects" TO execom_service USING (true) WITH CHECK (true);
GRANT SELECT,INSERT,UPDATE,DELETE ON public."on_eri_contracts" TO anonymous;
GRANT SELECT,INSERT,UPDATE,DELETE ON public."on_eri_contracts" TO authenticated;
ALTER TABLE public."on_eri_contracts" ENABLE ROW LEVEL SECURITY;
CREATE POLICY execom_server_access ON public."on_eri_contracts" TO execom_service USING (true) WITH CHECK (true);
GRANT SELECT,INSERT,UPDATE,DELETE ON public."evidence" TO anonymous;
GRANT SELECT,INSERT,UPDATE,DELETE ON public."evidence" TO authenticated;
ALTER TABLE public."evidence" ENABLE ROW LEVEL SECURITY;
CREATE POLICY execom_server_access ON public."evidence" TO execom_service USING (true) WITH CHECK (true);
GRANT SELECT,INSERT,UPDATE,DELETE ON public."costs" TO anonymous;
GRANT SELECT,INSERT,UPDATE,DELETE ON public."costs" TO authenticated;
ALTER TABLE public."costs" ENABLE ROW LEVEL SECURITY;
CREATE POLICY execom_server_access ON public."costs" TO execom_service USING (true) WITH CHECK (true);
ALTER TABLE public."galea_preview_workspaces" ENABLE ROW LEVEL SECURITY;
CREATE POLICY execom_server_access ON public."galea_preview_workspaces" TO execom_service USING (true) WITH CHECK (true);
GRANT SELECT,INSERT,UPDATE,DELETE ON public."matter_status_events" TO anonymous;
GRANT SELECT,INSERT,UPDATE,DELETE ON public."matter_status_events" TO authenticated;
ALTER TABLE public."matter_status_events" ENABLE ROW LEVEL SECURITY;
CREATE POLICY execom_server_access ON public."matter_status_events" TO execom_service USING (true) WITH CHECK (true);
GRANT SELECT,INSERT,UPDATE,DELETE ON public."commercialization_matters" TO anonymous;
GRANT SELECT,INSERT,UPDATE,DELETE ON public."commercialization_matters" TO authenticated;
ALTER TABLE public."commercialization_matters" ENABLE ROW LEVEL SECURITY;
CREATE POLICY execom_server_access ON public."commercialization_matters" TO execom_service USING (true) WITH CHECK (true);
GRANT SELECT,INSERT,UPDATE,DELETE ON public."project_narrative_sections" TO anonymous;
GRANT SELECT,INSERT,UPDATE,DELETE ON public."project_narrative_sections" TO authenticated;
ALTER TABLE public."project_narrative_sections" ENABLE ROW LEVEL SECURITY;
CREATE POLICY execom_server_access ON public."project_narrative_sections" TO execom_service USING (true) WITH CHECK (true);
GRANT SELECT,INSERT,UPDATE,DELETE ON public."project_evidence_links" TO anonymous;
GRANT SELECT,INSERT,UPDATE,DELETE ON public."project_evidence_links" TO authenticated;
ALTER TABLE public."project_evidence_links" ENABLE ROW LEVEL SECURITY;
CREATE POLICY execom_server_access ON public."project_evidence_links" TO execom_service USING (true) WITH CHECK (true);
GRANT SELECT,INSERT,UPDATE,DELETE ON public."cost_imports" TO anonymous;
GRANT SELECT,INSERT,UPDATE,DELETE ON public."cost_imports" TO authenticated;
ALTER TABLE public."cost_imports" ENABLE ROW LEVEL SECURITY;
CREATE POLICY execom_server_access ON public."cost_imports" TO execom_service USING (true) WITH CHECK (true);
GRANT SELECT,INSERT,UPDATE,DELETE ON public."cost_line_items" TO anonymous;
GRANT SELECT,INSERT,UPDATE,DELETE ON public."cost_line_items" TO authenticated;
ALTER TABLE public."cost_line_items" ENABLE ROW LEVEL SECURITY;
CREATE POLICY execom_server_access ON public."cost_line_items" TO execom_service USING (true) WITH CHECK (true);
GRANT SELECT,INSERT,UPDATE,DELETE ON public."cost_project_splits" TO anonymous;
GRANT SELECT,INSERT,UPDATE,DELETE ON public."cost_project_splits" TO authenticated;
ALTER TABLE public."cost_project_splits" ENABLE ROW LEVEL SECURITY;
CREATE POLICY execom_server_access ON public."cost_project_splits" TO execom_service USING (true) WITH CHECK (true);
GRANT SELECT,INSERT,UPDATE,DELETE ON public."federal_claim_snapshots" TO anonymous;
GRANT SELECT,INSERT,UPDATE,DELETE ON public."federal_claim_snapshots" TO authenticated;
ALTER TABLE public."federal_claim_snapshots" ENABLE ROW LEVEL SECURITY;
CREATE POLICY execom_server_access ON public."federal_claim_snapshots" TO execom_service USING (true) WITH CHECK (true);
GRANT SELECT,INSERT,UPDATE,DELETE ON public."federal_line_values" TO anonymous;
GRANT SELECT,INSERT,UPDATE,DELETE ON public."federal_line_values" TO authenticated;
ALTER TABLE public."federal_line_values" ENABLE ROW LEVEL SECURITY;
CREATE POLICY execom_server_access ON public."federal_line_values" TO execom_service USING (true) WITH CHECK (true);
GRANT SELECT,INSERT,UPDATE,DELETE ON public."federal_calculation_steps" TO anonymous;
GRANT SELECT,INSERT,UPDATE,DELETE ON public."federal_calculation_steps" TO authenticated;
ALTER TABLE public."federal_calculation_steps" ENABLE ROW LEVEL SECURITY;
CREATE POLICY execom_server_access ON public."federal_calculation_steps" TO execom_service USING (true) WITH CHECK (true);
GRANT SELECT,INSERT,UPDATE,DELETE ON public."provincial_claim_snapshots" TO anonymous;
GRANT SELECT,INSERT,UPDATE,DELETE ON public."provincial_claim_snapshots" TO authenticated;
ALTER TABLE public."provincial_claim_snapshots" ENABLE ROW LEVEL SECURITY;
CREATE POLICY execom_server_access ON public."provincial_claim_snapshots" TO execom_service USING (true) WITH CHECK (true);
GRANT SELECT,INSERT,UPDATE,DELETE ON public."provincial_line_values" TO anonymous;
GRANT SELECT,INSERT,UPDATE,DELETE ON public."provincial_line_values" TO authenticated;
ALTER TABLE public."provincial_line_values" ENABLE ROW LEVEL SECURITY;
CREATE POLICY execom_server_access ON public."provincial_line_values" TO execom_service USING (true) WITH CHECK (true);
GRANT SELECT,INSERT,UPDATE,DELETE ON public."assistance_items" TO anonymous;
GRANT SELECT,INSERT,UPDATE,DELETE ON public."assistance_items" TO authenticated;
ALTER TABLE public."assistance_items" ENABLE ROW LEVEL SECURITY;
CREATE POLICY execom_server_access ON public."assistance_items" TO execom_service USING (true) WITH CHECK (true);
GRANT SELECT,INSERT,UPDATE,DELETE ON public."claim_snapshots" TO anonymous;
GRANT SELECT,INSERT,UPDATE,DELETE ON public."claim_snapshots" TO authenticated;
ALTER TABLE public."claim_snapshots" ENABLE ROW LEVEL SECURITY;
CREATE POLICY execom_server_access ON public."claim_snapshots" TO execom_service USING (true) WITH CHECK (true);
GRANT SELECT,INSERT,UPDATE,DELETE ON public."claim_years" TO anonymous;
GRANT SELECT,INSERT,UPDATE,DELETE ON public."claim_years" TO authenticated;
ALTER TABLE public."claim_years" ENABLE ROW LEVEL SECURITY;
CREATE POLICY execom_server_access ON public."claim_years" TO execom_service USING (true) WITH CHECK (true);
GRANT SELECT,INSERT,UPDATE,DELETE ON public."claim_contacts" TO anonymous;
GRANT SELECT,INSERT,UPDATE,DELETE ON public."claim_contacts" TO authenticated;
ALTER TABLE public."claim_contacts" ENABLE ROW LEVEL SECURITY;
CREATE POLICY execom_server_access ON public."claim_contacts" TO execom_service USING (true) WITH CHECK (true);
GRANT SELECT,INSERT,UPDATE,DELETE ON public."project_people" TO anonymous;
GRANT SELECT,INSERT,UPDATE,DELETE ON public."project_people" TO authenticated;
ALTER TABLE public."project_people" ENABLE ROW LEVEL SECURITY;
CREATE POLICY execom_server_access ON public."project_people" TO execom_service USING (true) WITH CHECK (true);
GRANT SELECT,INSERT,UPDATE,DELETE ON public."review_issues" TO anonymous;
GRANT SELECT,INSERT,UPDATE,DELETE ON public."review_issues" TO authenticated;
ALTER TABLE public."review_issues" ENABLE ROW LEVEL SECURITY;
CREATE POLICY execom_server_access ON public."review_issues" TO execom_service USING (true) WITH CHECK (true);
GRANT SELECT,INSERT,UPDATE,DELETE ON public."export_bundles" TO anonymous;
GRANT SELECT,INSERT,UPDATE,DELETE ON public."export_bundles" TO authenticated;
ALTER TABLE public."export_bundles" ENABLE ROW LEVEL SECURITY;
CREATE POLICY execom_server_access ON public."export_bundles" TO execom_service USING (true) WITH CHECK (true);
GRANT SELECT,INSERT,UPDATE,DELETE ON public."provincial_project_breakdowns" TO anonymous;
GRANT SELECT,INSERT,UPDATE,DELETE ON public."provincial_project_breakdowns" TO authenticated;
ALTER TABLE public."provincial_project_breakdowns" ENABLE ROW LEVEL SECURITY;
CREATE POLICY execom_server_access ON public."provincial_project_breakdowns" TO execom_service USING (true) WITH CHECK (true);
GRANT SELECT,INSERT,UPDATE,DELETE ON public."review_rules" TO anonymous;
GRANT SELECT,INSERT,UPDATE,DELETE ON public."review_rules" TO authenticated;
ALTER TABLE public."review_rules" ENABLE ROW LEVEL SECURITY;
CREATE POLICY execom_server_access ON public."review_rules" TO execom_service USING (true) WITH CHECK (true);
GRANT SELECT,INSERT,UPDATE,DELETE ON public."cost_line_classifications" TO anonymous;
GRANT SELECT,INSERT,UPDATE,DELETE ON public."cost_line_classifications" TO authenticated;
ALTER TABLE public."cost_line_classifications" ENABLE ROW LEVEL SECURITY;
CREATE POLICY execom_server_access ON public."cost_line_classifications" TO execom_service USING (true) WITH CHECK (true);
GRANT SELECT,INSERT,UPDATE,DELETE ON public."cost_line_project_splits" TO anonymous;
GRANT SELECT,INSERT,UPDATE,DELETE ON public."cost_line_project_splits" TO authenticated;
ALTER TABLE public."cost_line_project_splits" ENABLE ROW LEVEL SECURITY;
CREATE POLICY execom_server_access ON public."cost_line_project_splits" TO execom_service USING (true) WITH CHECK (true);
GRANT SELECT,INSERT,UPDATE,DELETE ON public."recalc_runs" TO authenticated;
ALTER TABLE public."recalc_runs" ENABLE ROW LEVEL SECURITY;
CREATE POLICY execom_server_access ON public."recalc_runs" TO execom_service USING (true) WITH CHECK (true);
GRANT SELECT,INSERT,UPDATE,DELETE ON public."provincial_employee_time" TO anonymous;
GRANT SELECT,INSERT,UPDATE,DELETE ON public."provincial_employee_time" TO authenticated;
ALTER TABLE public."provincial_employee_time" ENABLE ROW LEVEL SECURITY;
CREATE POLICY execom_server_access ON public."provincial_employee_time" TO execom_service USING (true) WITH CHECK (true);
GRANT SELECT,INSERT,UPDATE,DELETE ON public."claim_recalc_locks" TO authenticated;
ALTER TABLE public."claim_recalc_locks" ENABLE ROW LEVEL SECURITY;
CREATE POLICY execom_server_access ON public."claim_recalc_locks" TO execom_service USING (true) WITH CHECK (true);
GRANT SELECT,INSERT,UPDATE,DELETE ON public."incorporation_intakes" TO anonymous;
GRANT SELECT,INSERT,UPDATE,DELETE ON public."incorporation_intakes" TO authenticated;
ALTER TABLE public."incorporation_intakes" ENABLE ROW LEVEL SECURITY;
CREATE POLICY execom_server_access ON public."incorporation_intakes" TO execom_service USING (true) WITH CHECK (true);
GRANT SELECT,INSERT,UPDATE,DELETE ON public."approved_snapshots" TO anonymous;
GRANT SELECT,INSERT,UPDATE,DELETE ON public."approved_snapshots" TO authenticated;
ALTER TABLE public."approved_snapshots" ENABLE ROW LEVEL SECURITY;
CREATE POLICY execom_server_access ON public."approved_snapshots" TO execom_service USING (true) WITH CHECK (true);
GRANT SELECT,INSERT,UPDATE,DELETE ON public."generated_artifacts" TO anonymous;
GRANT SELECT,INSERT,UPDATE,DELETE ON public."generated_artifacts" TO authenticated;
ALTER TABLE public."generated_artifacts" ENABLE ROW LEVEL SECURITY;
CREATE POLICY execom_server_access ON public."generated_artifacts" TO execom_service USING (true) WITH CHECK (true);
GRANT SELECT,INSERT,UPDATE,DELETE ON public."ip_transfer_intakes" TO anonymous;
GRANT SELECT,INSERT,UPDATE,DELETE ON public."ip_transfer_intakes" TO authenticated;
ALTER TABLE public."ip_transfer_intakes" ENABLE ROW LEVEL SECURITY;
CREATE POLICY execom_server_access ON public."ip_transfer_intakes" TO execom_service USING (true) WITH CHECK (true);
GRANT SELECT,INSERT,UPDATE,DELETE ON public."licensing_intakes" TO anonymous;
GRANT SELECT,INSERT,UPDATE,DELETE ON public."licensing_intakes" TO authenticated;
ALTER TABLE public."licensing_intakes" ENABLE ROW LEVEL SECURITY;
CREATE POLICY execom_server_access ON public."licensing_intakes" TO execom_service USING (true) WITH CHECK (true);
GRANT SELECT,INSERT,UPDATE,DELETE ON public."trademark_goods_services" TO anonymous;
GRANT SELECT,INSERT,UPDATE,DELETE ON public."trademark_goods_services" TO authenticated;
ALTER TABLE public."trademark_goods_services" ENABLE ROW LEVEL SECURITY;
CREATE POLICY execom_server_access ON public."trademark_goods_services" TO execom_service USING (true) WITH CHECK (true);
GRANT SELECT,INSERT,UPDATE,DELETE ON public."trademark_intakes" TO anonymous;
GRANT SELECT,INSERT,UPDATE,DELETE ON public."trademark_intakes" TO authenticated;
ALTER TABLE public."trademark_intakes" ENABLE ROW LEVEL SECURITY;
CREATE POLICY execom_server_access ON public."trademark_intakes" TO execom_service USING (true) WITH CHECK (true);
GRANT SELECT,INSERT,UPDATE,DELETE ON public."prototype_assessments" TO anonymous;
GRANT SELECT,INSERT,UPDATE,DELETE ON public."prototype_assessments" TO authenticated;
ALTER TABLE public."prototype_assessments" ENABLE ROW LEVEL SECURITY;
CREATE POLICY execom_server_access ON public."prototype_assessments" TO execom_service USING (true) WITH CHECK (true);
GRANT SELECT,INSERT,UPDATE,DELETE ON public."matter_summary" TO authenticated;
GRANT SELECT,INSERT,UPDATE,DELETE ON public."regions" TO anonymous;
GRANT SELECT,INSERT,UPDATE,DELETE ON public."regions" TO authenticated;
ALTER TABLE public."regions" ENABLE ROW LEVEL SECURITY;
CREATE POLICY execom_server_access ON public."regions" TO execom_service USING (true) WITH CHECK (true);
GRANT SELECT,INSERT,UPDATE,DELETE ON public."benchmark_categories" TO anonymous;
GRANT SELECT,INSERT,UPDATE,DELETE ON public."benchmark_categories" TO authenticated;
ALTER TABLE public."benchmark_categories" ENABLE ROW LEVEL SECURITY;
CREATE POLICY execom_server_access ON public."benchmark_categories" TO execom_service USING (true) WITH CHECK (true);
GRANT SELECT,INSERT,UPDATE,DELETE ON public."benchmark_values" TO anonymous;
GRANT SELECT,INSERT,UPDATE,DELETE ON public."benchmark_values" TO authenticated;
ALTER TABLE public."benchmark_values" ENABLE ROW LEVEL SECURITY;
CREATE POLICY execom_server_access ON public."benchmark_values" TO execom_service USING (true) WITH CHECK (true);
GRANT SELECT,INSERT,UPDATE,DELETE ON public."sources" TO anonymous;
GRANT SELECT,INSERT,UPDATE,DELETE ON public."sources" TO authenticated;
ALTER TABLE public."sources" ENABLE ROW LEVEL SECURITY;
CREATE POLICY execom_server_access ON public."sources" TO execom_service USING (true) WITH CHECK (true);
GRANT SELECT,INSERT,UPDATE,DELETE ON public."benchmark_source_links" TO anonymous;
GRANT SELECT,INSERT,UPDATE,DELETE ON public."benchmark_source_links" TO authenticated;
ALTER TABLE public."benchmark_source_links" ENABLE ROW LEVEL SECURITY;
CREATE POLICY execom_server_access ON public."benchmark_source_links" TO execom_service USING (true) WITH CHECK (true);
GRANT SELECT,INSERT,UPDATE,DELETE ON public."execom_tier_assumptions" TO anonymous;
GRANT SELECT,INSERT,UPDATE,DELETE ON public."execom_tier_assumptions" TO authenticated;
ALTER TABLE public."execom_tier_assumptions" ENABLE ROW LEVEL SECURITY;
CREATE POLICY execom_server_access ON public."execom_tier_assumptions" TO execom_service USING (true) WITH CHECK (true);
GRANT SELECT,INSERT,UPDATE,DELETE ON public."methodology_configs" TO anonymous;
GRANT SELECT,INSERT,UPDATE,DELETE ON public."methodology_configs" TO authenticated;
ALTER TABLE public."methodology_configs" ENABLE ROW LEVEL SECURITY;
CREATE POLICY execom_server_access ON public."methodology_configs" TO execom_service USING (true) WITH CHECK (true);
GRANT SELECT,INSERT,UPDATE,DELETE ON public."calculator_runs" TO anonymous;
GRANT SELECT,INSERT,UPDATE,DELETE ON public."calculator_runs" TO authenticated;
ALTER TABLE public."calculator_runs" ENABLE ROW LEVEL SECURITY;
CREATE POLICY execom_server_access ON public."calculator_runs" TO execom_service USING (true) WITH CHECK (true);
GRANT EXECUTE ON FUNCTION public.update_timestamp() TO anonymous;
GRANT EXECUTE ON FUNCTION public.update_timestamp() TO authenticated;
GRANT EXECUTE ON FUNCTION public.sync_matter_status() TO anonymous;
GRANT EXECUTE ON FUNCTION public.sync_matter_status() TO authenticated;
GRANT EXECUTE ON FUNCTION public.enforce_status_transition() TO anonymous;
GRANT EXECUTE ON FUNCTION public.enforce_status_transition() TO authenticated;
GRANT EXECUTE ON FUNCTION public.prevent_snapshot_mutation() TO anonymous;
GRANT EXECUTE ON FUNCTION public.prevent_snapshot_mutation() TO authenticated;
GRANT EXECUTE ON FUNCTION public.sync_matter_status_generic() TO anonymous;
GRANT EXECUTE ON FUNCTION public.sync_matter_status_generic() TO authenticated;
GRANT EXECUTE ON FUNCTION public.set_updated_at() TO anonymous;
GRANT EXECUTE ON FUNCTION public.set_updated_at() TO authenticated;
GRANT EXECUTE ON FUNCTION public.set_prototype_assessments_updated_at() TO anonymous;
GRANT EXECUTE ON FUNCTION public.set_prototype_assessments_updated_at() TO authenticated;
GRANT EXECUTE ON FUNCTION public.is_super_admin() TO anonymous;
GRANT EXECUTE ON FUNCTION public.is_super_admin() TO authenticated;
GRANT EXECUTE ON FUNCTION public.prevent_privilege_escalation() TO anonymous;
GRANT EXECUTE ON FUNCTION public.prevent_privilege_escalation() TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_my_profile() TO anonymous;
GRANT EXECUTE ON FUNCTION public.get_my_profile() TO authenticated;
GRANT EXECUTE ON FUNCTION public.user_belongs_to_company(target_company_id uuid) TO anonymous;
GRANT EXECUTE ON FUNCTION public.user_belongs_to_company(target_company_id uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.is_execom_staff() TO anonymous;
GRANT EXECUTE ON FUNCTION public.is_execom_staff() TO authenticated;
GRANT EXECUTE ON FUNCTION public.handle_new_user() TO anonymous;
GRANT EXECUTE ON FUNCTION public.handle_new_user() TO authenticated;
GRANT EXECUTE ON FUNCTION public.claim_year_company(cy_id uuid) TO anonymous;
GRANT EXECUTE ON FUNCTION public.claim_year_company(cy_id uuid) TO authenticated;
REVOKE ALL ON SCHEMA portal_auth FROM PUBLIC,anon,anonymous,authenticated,legacy_authenticated,service_role,execom_service;
REVOKE ALL ON ALL TABLES IN SCHEMA portal_auth FROM PUBLIC,anon,anonymous,authenticated,legacy_authenticated,service_role,execom_service;
COMMIT;
