-- ════════════════════════════════════════════════════════════════════════════
-- Migration 008: Recalculation pipeline state tracking
-- Part of Commit 3: feat/sred-recalc-pipeline-phase-1
-- ════════════════════════════════════════════════════════════════════════════

-- ── Recalculation run history ──

CREATE TABLE IF NOT EXISTS recalc_runs (
  id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  claim_year_id   uuid NOT NULL REFERENCES claim_years(id) ON DELETE CASCADE,
  status          text NOT NULL CHECK (status IN ('running', 'succeeded', 'failed', 'cancelled')),
  trigger_source  text,           -- e.g. 'cost_import', 'classification_change', 'manual'
  trigger_entity  text,           -- e.g. 'cost_line_items', 'cost_line_classifications'
  trigger_entity_id text,         -- the specific row id that changed
  initiated_by    uuid REFERENCES profiles(id),
  started_at      timestamptz NOT NULL DEFAULT now(),
  finished_at     timestamptz,
  error_message   text,
  provisional_federal_qe  numeric(14,2),
  final_federal_qe        numeric(14,2),
  provinces_processed      jsonb,   -- ["AB","BC","ON"]
  provincial_credits       jsonb,   -- [{provinceCode, creditAmount, federalAssistanceAmount}]
  review_summary           jsonb,   -- {blockers, warnings, info}
  metadata                 jsonb    -- extensible bucket for future fields
);

-- ── Per-claim-year lock to prevent concurrent recalculation ──

CREATE TABLE IF NOT EXISTS claim_recalc_locks (
  claim_year_id   uuid PRIMARY KEY REFERENCES claim_years(id) ON DELETE CASCADE,
  locked_at       timestamptz NOT NULL DEFAULT now(),
  locked_by       uuid REFERENCES profiles(id),
  run_id          uuid REFERENCES recalc_runs(id) ON DELETE SET NULL
);

-- ── Indexes ──

CREATE INDEX IF NOT EXISTS idx_recalc_runs_claim_year
  ON recalc_runs(claim_year_id);

CREATE INDEX IF NOT EXISTS idx_recalc_runs_status
  ON recalc_runs(status);

CREATE INDEX IF NOT EXISTS idx_recalc_runs_started_at
  ON recalc_runs(started_at DESC);

-- ── Row Level Security ──

ALTER TABLE recalc_runs ENABLE ROW LEVEL SECURITY;
ALTER TABLE claim_recalc_locks ENABLE ROW LEVEL SECURITY;

-- recalc_runs: same access pattern as claim_years
CREATE POLICY recalc_runs_access ON recalc_runs
  FOR ALL
  USING (
    user_belongs_to_company(
      (SELECT company_id FROM claim_years WHERE id = claim_year_id)
    )
    OR is_execom_staff()
  );

-- claim_recalc_locks: same access pattern
CREATE POLICY claim_recalc_locks_access ON claim_recalc_locks
  FOR ALL
  USING (
    user_belongs_to_company(
      (SELECT company_id FROM claim_years WHERE id = claim_year_id)
    )
    OR is_execom_staff()
  );

-- ── Add generated_by column to assistance_items for provenance tracking ──
-- This distinguishes manual entries from recalculation-generated entries.

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'assistance_items' AND column_name = 'generated_by'
  ) THEN
    ALTER TABLE assistance_items ADD COLUMN generated_by text;
    COMMENT ON COLUMN assistance_items.generated_by IS
      'Provenance tag: NULL or manual = user-entered; recalc_pipeline = generated by recalculation engine';
  END IF;
END $$;

-- ── Add run_id column to assistance_items for traceability ──

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'assistance_items' AND column_name = 'recalc_run_id'
  ) THEN
    ALTER TABLE assistance_items ADD COLUMN recalc_run_id uuid REFERENCES recalc_runs(id) ON DELETE SET NULL;
  END IF;
END $$;
