-- ════════════════════════════════════════════════════════════════════════════
-- Migration 013: Close remaining drift from migration 008
--
-- Migration 008 tried to add two columns to assistance_items:
--   - generated_by    text          (provenance tag)
--   - recalc_run_id   uuid FK       (traceability to recalc_runs.id)
--
-- 008 never fully applied in production. The recalc_runs and
-- claim_recalc_locks tables made it in; RLS on them did not (fixed in
-- migration 012); and neither of the assistance_items columns landed.
--
-- Verified empty at time of writing (2026-04-11):
--   recalc_runs          count = 0
--   claim_recalc_locks   count = 0
--   assistance_items     count = 0
--
-- So this migration is safe to apply — there is no data to backfill and
-- nothing currently depends on either column. It simply closes the drift
-- so that when the recalc pipeline is activated, the schema matches what
-- the pipeline code expects.
--
-- Idempotent: guarded by information_schema checks, same pattern 008 used.
-- ════════════════════════════════════════════════════════════════════════════

do $$
begin
  if not exists (
    select 1 from information_schema.columns
    where table_schema = 'public'
      and table_name   = 'assistance_items'
      and column_name  = 'generated_by'
  ) then
    alter table public.assistance_items
      add column generated_by text;

    comment on column public.assistance_items.generated_by is
      'Provenance tag: NULL or ''manual'' = user-entered; ''recalc_pipeline'' = generated by the recalculation engine.';
  end if;
end $$;

do $$
begin
  if not exists (
    select 1 from information_schema.columns
    where table_schema = 'public'
      and table_name   = 'assistance_items'
      and column_name  = 'recalc_run_id'
  ) then
    alter table public.assistance_items
      add column recalc_run_id uuid
      references public.recalc_runs(id) on delete set null;
  end if;
end $$;
